name: Package and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [payment, atm]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for SonarCloud analysis nuget

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.module }}/package-lock.json

    - name: Install dependencies
      run: cd ${{ matrix.module }} && npm ci

    - name: Run tests
      run: cd ${{ matrix.module }} && npm run test:cov

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ${{ matrix.module }}/
        args: >
          -Dsonar.organization=gabrielfmh
          -Dsonar.projectKey=lab-2025-ii-pds-u2-03-nest-GabrielFMH_${{ matrix.module }}
          -Dsonar.sources=src
          -Dsonar.tests=test
          -Dsonar.test.inclusions=**/*.spec.ts
          -Dsonar.coverage.exclusions=**/*.spec.ts
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        module: [payment, atm]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.module }}/package-lock.json
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies
      run: cd ${{ matrix.module }} && npm ci

    - name: Build
      run: cd ${{ matrix.module }} && npm run build

    - name: Publish to GitHub Packages
      run: cd ${{ matrix.module }} && npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}